daily_statistic:
  cron: "5 0 * * *"
  class: "Charts::DailyStatistic"
  queue: critical

block_statistic:
  cron: "*/10 * * * *"
  class: "Charts::BlockStatistic"
  queue: critical

epoch_statistic:
  cron: "*/30 * * * *"
  class: "Charts::EpochStatistic"
  queue: critical

chart_forked_event_processor:
  cron: "30 0 * * *"
  class: "Charts::ForkedEventProcessor"
  queue: critical

cal_unclaimed_compensation:
  cron: "0 */1 * * *"
  class: "DaoContractUnclaimedCompensationGenerator"

cal_address_average_deposit_time:
  cron: "0 */6 * * *"
  class: "AddressAverageDepositTimeGenerator"

cal_average_block_time:
  cron: "10 0 * * *"
  class: "AverageBlockTimeGenerator"
